config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root "rooms#new"
  get "rooms/:number", to: "rooms#show", as: "room"
  get "rooms/:number/join", to: "join#new", as: "join_room"
  resources :rooms, only: %i[show create update destroy] do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :room_users, dependent: :destroy

  validates :name, presence: true
  validates :number, presence: true, uniqueness: true

  scope :default, -> { where(private: false) }
  scope :private_rooms, -> { where(private: true) }
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable,
         :omniauthable, omniauth_providers: %i[github]

  def self.from_omniauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider) do |user|
      user.uid = auth.uid
      user.name = auth.info.name
      user.username = auth.info.nickname
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.avatar_image_url = auth.info.image
      user.skip_confirmation!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[show update destroy]

  def new
    @room = Room.new
  end

  def create
    @room = Rooms::CreateRoomService.new(
      display_name: room_params[:display_name],
      user: current_user
    ).call

    sign_in @room.user unless user_signed_in?

    redirect_to room_path(number: @room.number)
  rescue StandardError => e
    flash[:error] = e.message
    render :new
  end

  def show
  end

  def update
  end

  def destroy
  end

  private

  def room_params
    params.permit(:display_name)
  end

  def set_room
    @room = Room.find_by(number: params[:number])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def github
      @user = User.from_omniauth(request.env["omniauth.auth"])
      sign_in_and_redirect @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag :div, message, class: "alert alert-#{type} p-2 text-center" %>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar bg-zinc-800 text-zinc-300 flex items-center p-4 border-b border-zinc-700" role="navigation" aria-label="main navigation">
  <% if @room.present? %>
    <div>
      <%= link_to "scrum poker", root_path, class: "text-white text-2xl font-medium" %>
    </div>
    <div class="flex-grow text-center">
      <%= yield :navbar %>
    </div>
  <% else %>
    <div class="flex-grow">
      <%= link_to "scrum poker", root_path, class: "text-white text-2xl font-medium" %>
    </div>
  <% end %>
  <div class="">
    <% if user_signed_in? %>
      <div class="flex items-center gap-2">
        <div>
          <%= link_to current_user.guest ? current_user.name : current_user.username, edit_user_registration_path, class: "text-white font-bold" %>
        </div>
        <!-- Profile dropdown -->
        <div id="profile-dropdown"
          data-controller="dropdown-menu"
          class="relative ml-2 flex-shrink-0">
          <div class="flex items-center">
            <button data-action="click->dropdown-menu#toggle" type="button" class="flex rounded-full bg-white focus:outline-none focus:ring-2 focus:ring-gray-900 focus:ring-offset-2" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
              <span class="sr-only">Open user menu</span>
              <%= image_tag current_user.avatar_image_url, class: "rounded-full w-8 h-8", alt: current_user.username %>
            </button>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
              <path fill-rule="evenodd" d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z" clip-rule="evenodd" />
            </svg>
          </div>

          <!--
            Dropdown menu, show/hide based on menu state.

            Entering: "transition ease-out duration-100"
            From: "transform opacity-0 scale-95"
            To: "transform opacity-100 scale-100"
            Leaving: "transition ease-in duration-75"
            From: "transform opacity-100 scale-100"
            To: "transform opacity-0 scale-95"
          -->
          <div data-dropdown-menu-target="dropdownMenu" class="dropdown-menu absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
            <!-- Active: "bg-gray-100", Not Active: "" -->
            <%= link_to "Your Profile", edit_user_registration_path(current_user), class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, data: { turbo_method: "delete" }, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" %>
          </div>
        </div>
      </div>
  </div>
</div>
    <% else %>
      <% unless current_page?(new_user_session_path) %>
        <%= button_to user_github_omniauth_authorize_path,
          method: :post,
          data: { turbo: "false" },
          class: "btn btn-primary w-full block text-center" do %>
          <div class="flex items-center justify-center gap-2">
            <svg height="32" aria-hidden="true" viewBox="0 0 16 16" version="1.1" width="32">
              <path fill="white" d="M8 0c4.42 0 8 3.58 8 8a8.013 8.013 0 0 1-5.45 7.59c-.4.08-.55-.17-.55-.38 0-.27.01-1.13.01-2.2 0-.75-.25-1.23-.54-1.48 1.78-.2 3.65-.88 3.65-3.95 0-.88-.31-1.59-.82-2.15.08-.2.36-1.02-.08-2.12 0 0-.67-.22-2.2.82-.64-.18-1.32-.27-2-.27-.68 0-1.36.09-2 .27-1.53-1.03-2.2-.82-2.2-.82-.44 1.1-.16 1.92-.08 2.12-.51.56-.82 1.28-.82 2.15 0 3.06 1.86 3.75 3.64 3.95-.23.2-.44.55-.51 1.07-.46.21-1.61.55-2.33-.66-.15-.24-.6-.83-1.23-.82-.67.01-.27.38.01.53.34.19.73.9.82 1.13.16.45.68 1.31 2.69.94 0 .67.01 1.3.01 1.49 0 .21-.15.45-.55.38A7.995 7.995 0 0 1 0 8c0-4.42 3.58-8 8-8Z"></path>
            </svg>
            <div>Sign in with GitHub</div>
          </div>
        <% end %>
      <% end %>
    <% end %>
    </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game of Scrum - <%= content_for?(:title) ? yield(:title) : "DEFAULT" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>

  <body>
    <%= render "layouts/flash" %>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<% content_for(:title) { "Scrum Poker" } %>
<div class="w-2/3 mx-auto p-16">
  <h1 class="text-3xl font-bold my-2">scrum poker</h1>
  <p>Welcome to the Game of Scrum. Ready to play?</p>
</div>

app/views/rooms/new.html.erb
<% content_for :title, "Create Your Room" %>

<div class="w-full md:w-1/3 mx-auto p-8">
  <div class="py-4">
    <h1 class="text-3xl font-bold mb-2">Create Your Room</h1>
    <% if user_signed_in? %>
      <p class="text-zinc-500">You're one step away from creating a room.</p>
    <% else %>
      <p class="text-zinc-500">We just need to know what to call you, and we'll create a room for you.</p>
    <% end %>
  </div>
  <%= form_for @room, url: rooms_path do %>
    <% unless user_signed_in? %>
      <div class="mt-4">
        <%= label_tag :display_name, "Display name" %>
        <%= text_field_tag :display_name, nil, class: "w-full border rounded p-2" %>
        <div class="help-text">Enter your name that will be displayed to all guests.</div>
      </div>
    <% end %>
    <div class="mt-4">
      <%= submit_tag "Create Room", class: "btn btn-primary w-full" %>
      <p class="my-4 text-center text-zinc-500">Once your room has been created you can invite guests to join you.</p>
    </div>
  <% end %>
</div>

app/views/rooms/show.html.erb
<% content_for(:title) { "Room #{@room.number}" } %>
<% content_for(:navbar) do %>
  <div class="text-zinc-400">Room #&nbsp;<span class="text-white"><%= @room.number %> </span></div>
  <div class="flex items-center justify-center mt-2">
    <%= link_to join_room_url, join_room_url(@room.number), class: "inline-block text-sm text-zinc-300 underline" %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4 cursor-pointer ml-1">
      <path stroke-linecap="round" stroke-linejoin="round" d="M15.666 3.888A2.25 2.25 0 0013.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 01-.75.75H9a.75.75 0 01-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 01-2.25 2.25H6.75A2.25 2.25 0 014.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 011.927-.184" />
    </svg>
  </div>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>